name: Update Mod Cache

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:

env:
  CONFIGURATION: Release
  PROJECT_FILE: "Internal.csproj"
  WORKING_DIRECTORY: "Internal"
  OUTPUT_PATH: "Output"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        git-config-name: Scribe-Bot
        branch: gh-pages-test
        folder: "resources"
        target-folder: "test"
        token: ${{ secrets.DEPLOY_TOKEN }}
